# config.yml
cookingWorkshop:
  outputSlot: 30
  backButtonSlot: 0
  ingredientInputSlots:
    - 18
    - 19
    - 27
    - 28
    - 36
    - 37
  recipeDisplaySlots:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
  cookingGuiRows: 6
  guiClickSound: "ui.button.click"
  guiClickSoundVolume: 1.0
  guiClickSoundPitch: 1.0
  craftingCustomModelData: 1000

  # GUI Titles
  guiTitle: "&8Cooking Workshop"
  recipeListTitle: "&8Cooking Recipes"
  recipeDetailTitle: "&8Recipe: {recipe_name}"

  # GUI Item Configurations
  backButtonItem:
    material: ARROW
    name: "&aBack to Recipes"
    lore:
      - "&7Click to return to the recipe list."
  nextPageItem:
    material: ARROW
    name: "&aNext Page"
    lore:
      - "&7Click to view the next page of recipes."
  prevPageItem:
    material: ARROW
    name: "&aPrevious Page"
    lore:
      - "&7Click to view the previous page of recipes."
  emptySlotItem:
    material: BLACK_STAINED_GLASS_PANE
    name: " "
    lore: []
  ingredientPlaceholderItem:
    material: GRAY_STAINED_GLASS_PANE
    name: "&7Required Ingredient"
    lore:
      - "&7Place your ingredients here."
  craftButtonItem:
    material: ANVIL
    name: "&aCraft"
    lore:
      - "&7Click to craft the selected recipe."

  # Output Item Lore
  outputItemLore:
    confirm: "&aClick to confirm recipe and place ingredients!"
    craft: "&aClick to Craft!"
    success: "&aCrafting successful!"
    failure: "&cCrafting failed! Check ingredients."
